version: '3'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - APP_SETTINGS=DevelopmentConfig
      - DATABASE_URL=postgresql://username:password@postgres:5432/dbname
      - SECRET_KEY=fdkjshfhjsdfdskfdsfdcbsjdkfdsdf
    depends_on:
      - postgres


  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=dbname
